global:
  defaultTenant : 3e64ebae-38b5-46a0-b1ed-9ccee153a0ae
  tenants: foo bar

  images:
    containerRegistry:
      path: eu.gcr.io/kyma-project/incubator
    connector:
      dir: pr/
      version: "PR-250"
    director:
      dir: develop/
      version: "4ab44720"
    gateway:
      dir: pr/
      version: "PR-251"
    healthchecker:
      dir: develop/
      version: "26601526"
    schema_migrator:
      dir: develop/
      version: "2cc96dec"
    certs_setup_job:
      containerRegistry:
        path: eu.gcr.io/kyma-project
      dir: pr/
      version: "PR-5318"
    tests:
      e2e:
        dir: develop/
        version: "3c75146c"

  isLocalEnv: false
  
  director:
    port: 3000

  connector:
    port: 3000
    # If secrets do not exist they will be created
    secrets:
      ca:
        name: connector-service-app-ca
        namespace: kyma-integration
      rootCA:
        name: application-connector-certs
        namespace: istio-system
    # If key and certificate are not provided they will be generated
    caKey: ""
    caCertificate: ""

  gateway:
    host: compass-gateway
  
  istio:
    gateway:
      name: "kyma-gateway"
      namespace: "kyma-system"

  database:
    useEmbedded: true
    # Values for GCP managed PostgreSQL database
    managedGCP:
      serviceAccountKey: ""
      instanceConnectionName: ""
      dbUser: ""
      dbPassword: ""
      dbName: ""
      host: "localhost"
      hostPort: "5432"
      sslMode: ""
