apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-event-service
  labels:
    app: {{ .Release.Name }}-event-service
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Release.Name }}-event-service
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: {{ .Release.Name }}-event-service
        kyma-grafana: {{ .Values.eventService.deployment.labels.grafana }}
        kyma-alerts: {{ .Values.eventService.deployment.labels.alerts }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{.Release.Name }}-event-service
      containers:
      - name: {{ .Release.Name }}-event-service
        image: {{ .Values.global.eventServiceImage }}
        imagePullPolicy: {{ .Values.eventService.deployment.image.pullPolicy }}
        args:
        - "/eventservice"
        - "--externalAPIPort={{ .Values.eventService.deployment.args.externalAPIPort }}"
        - "--eventMeshURL=http://{{ .Release.Name }}.{{ .Release.Namespace }}"
        - "--eventsTargetURLV1={{ .Values.eventService.deployment.args.eventsTargetURLV1 }}"
        - "--eventsTargetURLV2={{ .Values.eventService.deployment.args.eventsTargetURLV2 }}"
        - "--maxRequestSize={{ .Values.eventService.deployment.args.maxRequestSize }}"
        - "--requestTimeout={{ .Values.eventService.deployment.args.requestTimeout }}"
        - "--requestLogging={{ .Values.eventService.deployment.args.requestLogging }}"
        - "--sourceId={{ .Release.Name }}"
        readinessProbe:
          httpGet:
            path: /v1/health
            port: {{ .Values.eventService.deployment.args.externalAPIPort }}
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /v1/health
            port: {{ .Values.eventService.deployment.args.externalAPIPort }}
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
        - containerPort: {{ .Values.eventService.deployment.args.externalAPIPort }}
          name: http-api-port
