kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Release.Name }}-application-gateway
  labels:
    app: {{ .Release.Name }}-application-gateway
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
  - kind: User
    name: system:serviceaccount:{{ .Release.Namespace }}:{{ .Release.Name }}-application-gateway
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-application-gateway
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Release.Name }}-event-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{.Release.Name }}-event-service
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Release.Name }}-event-service
  labels:
    app: {{ .Release.Name }}-application-gateway
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: ["*"]
  resources: ["namespaces", "subscriptions", "triggers"]
  verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Release.Name }}-event-service
  labels:
    app: {{ .Release.Name }}-application-gateway
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
subjects:
- kind: User
  name: system:serviceaccount:{{ .Release.Namespace }}:{{ .Release.Name }}-event-service
  apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-event-service
