apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-event-service
  labels:
    application: {{ .Release.Name }}
    app: {{ .Release.Name }}-event-service
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.eventService.service.externalapi.port }}
    protocol: TCP
    name: http-api-port
  selector:
    app: {{ .Release.Name }}-event-service
    release: {{ .Release.Name }}
